# Generated by Django 3.2.16 on 2023-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseQueries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, max_length=100)),
                ('hotp', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
