# Generated by Django 3.2.16 on 2023-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseQueries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
